// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Event {
    "protocolVersion": number;
    "type": string;
    "requestId"?: string;
    "runId"?: string;
    "sequence"?: number;
    "occurredAt"?: string;
    "data"?: any;
}
