// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as protocol$0 from "../../../../wojustme/otto/protocol/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "otto:runtime-event": protocol$0.Event;
        }
    }
}
