// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as RuntimeService from "./runtimeservice.js";
export {
    RuntimeService
};

export type {
    RuntimeInfo
} from "./models.js";
