// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface RuntimeInfo {
    "connected": boolean;
    "runtimeVersion": string;
    "protocolVersion": number;
}
