// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CancelRun(runID: string): $CancellablePromise<void> {
    return $Call.ByID(457355428, runID);
}

export function RespondToApproval(runID: string, approvalID: string, approved: boolean): $CancellablePromise<void> {
    return $Call.ByID(1180472200, runID, approvalID, approved);
}

export function RuntimeInfo(): $CancellablePromise<$models.RuntimeInfo> {
    return $Call.ByID(3640655591);
}

export function StartRun(message: string): $CancellablePromise<string> {
    return $Call.ByID(1103826288, message);
}
